# Claim challenges for Animal Kingdom: touch something in the area. See README.md.
Discovery Island:
  - title: Roots of Life
    description: Touch one of the Tree of Life's roots along the Discovery Island trails.
Africa:
  - title: Harambe Market
    description: Touch the Harambe Market arch.
Asia:
  - title: Prayer Wheels
    description: Touch one of the prayer wheels near Expedition Everest.
DinoLand U.S.A.:
  - title: Dino Touch
    description: Frown at the entrance to dino DinoLand.
Pandora:
  - title: Glowing Plants
    description: Touch one of the plants by the Na'vi River Journey. Hopefully it lights up.
