# Animal Kingdom challenges. See README.md for the fields.
# Areas: Discovery Island, Africa, Asia, "DinoLand U.S.A.", Pandora

- title: Tree of Life Carvings
  area: Discovery Island
  description: "Spot {animal from list} on the tree of life"
  difficulty: 3

- title: Night Blossom
  area: Pandora
  description: Drink a Night Blossom from Pongu Pongu.
  difficulty: 1

- title: Gorilla Spotting
  area: Africa
  description: Spot a gorilla on the Gorilla Falls Exploration Trail.
  difficulty: 2
