# Challenges that can be done in any park. See README.md for the fields.

- title: Hidden Mickey
  description: Find a Hidden Mickey. You can look up hidden Mickey Locations but you must see it.
  reward: 1

- title: Character Photo
  description: Get a photo with any costumed character. You do not have to wait in line.
  reward: 2

- title: Snack Attack
  description: Buy a snack you've never had before.
  reward: 1

- title: Back to Back
  description: Ride two different attractions within 45 minutes.
  reward: 3

- title: Guess the queue time
  description: Accurately guess the wait time of a ride. Timer stops when you get off the ride. You must be within 10%
  reward: 1

- title: Wait It Out
  description: Ride an attraction with a wait of 45 minutes or more.
  reward: 5

- title: GeoGuessr
  description: Visit the location of the photo.
  list: {from: geoguessr, count: 1}
  reward: 3

- title: Splish Splash
  description: Ride any water ride. One of you has to come off visibly wet.
  reward: 3

- title: Bluddle uddle um dum
  description: Wash your hands in a themed bathroom.
  reward: 1

- title: Pin Trading
  description: Trade a mystery pin for a pin from the park. 
  reward: 5